### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by zy-fang** [aster-ww/scNAME#1]
Hi, Hui

Could you please upload the real data set？

Best wishes,

Zhaoyu

**Comment by aster-ww** [comment]
Hi, Zhaoyu
You can download the real datasets at https://drive.google.com/drive/folders/1lmoo8imjW1hssSSbtuipTT90ABV8H_Q7?usp=sharing
Hoping this helps,
Wan Hui

**Comment by zy-fang** [comment]
Thank you very much!
