### ISSUE TITLE
non-default paramater issue

### ISSUE THREAD

**Issue by daniel-spies** [aster-ww/scNAME#2]
Hi there, thanks for the great tool !

I started testing a few setups and noticed that when using non-default parameters the tool crashes: e.g. highly_genes have to be converted to int as well as the dimension array is not adjusted automatically to the size of the highly_genes.

this is just a first observation, will report other bugs as I encounter them

best
Daniel

**Comment by aster-ww** [comment]
Hi, Daniel
We've fixed the issues you mentioned,
thank you for your helpful suggestions.

Best wishes, 
Hui
